### ISSUE TITLE
[유저] CRUD, 로그인&로그아웃, jwt

### ISSUE THREAD

**Issue by sunnyineverywhere** [EFUB/efub3-frontend-assignment-server#2]
# To-Do
- [x] 기능: 로그인
- [x] 기능: 회원가입
- [x] 기능: JWT 검증
- [x] 기능: JWT 자동화 어노테이션
- [x] 문서: API 문서 작성
- [x] 기능: 토큰으로 유저 정보 조회 시 작성글, 작성댓글, 좋아요한 글 반환
- [ ] 기능: 비밀번호 및 닉네임 수정
